# Generated by Django 5.1.8 on 2025-05-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='method_payment',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Перевод', 'Перевод')], default='Наличные', max_length=250, verbose_name='Способ оплаты'),
        ),
    ]
