# Generated by Django 5.1.7 on 2025-03-25 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_payments_user_alter_payments_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_payments', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
