# Generated by Django 5.1.7 on 2025-04-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payments',
            name='session_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ID сессии'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount_payment',
            field=models.PositiveIntegerField(verbose_name='Сумма оплаты'),
        ),
    ]
