# Generated by Django 5.1.7 on 2025-04-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_payments_link_payments_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount_payment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
