# Generated by Django 5.1.7 on 2025-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('id_stripe_product', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название для оплаты')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='training/', verbose_name='Превью')),
                ('description', models.TextField(max_length=200, verbose_name='Описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('id_stripe_product', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название для оплаты')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='training/', verbose_name='Превью')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('link_to_video', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
