# Generated by Django 5.1.7 on 2025-03-29 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_course_owner_alter_lesson_owner_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now,
                                       verbose_name='Дата начала подписки'),
            preserve_default=False,
        ),
    ]
