# Generated by Django 5.1.7 on 2025-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_lesson_created_at_lesson_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
