# Generated by Django 5.1.7 on 2025-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name_stripe_product',
            field=models.CharField(default='', max_length=100, verbose_name='Название для оплаты'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
