# Generated by Django 5.1.7 on 2025-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_lesson_name_stripe_product_alter_lesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_stripe_product',
            field=models.CharField(default='', max_length=100, verbose_name='Название для оплаты'),
        ),
    ]
