# Generated by Django 5.1.7 on 2025-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_course_name_stripe_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name_stripe_product',
            new_name='id_stripe_product',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name_stripe_product',
            new_name='id_stripe_product',
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
