# Generated by Django 5.1.7 on 2025-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_rename_name_stripe_product_course_id_stripe_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id_stripe_product',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название для оплаты'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id_stripe_product',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название для оплаты'),
        ),
    ]
